invalid old_version

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -44,6 +44,10 @@ jobs:
         run: |
           set -euxo pipefail
           old_version="$(grep -Pom1 "VERSION \K[0-9.]+(?=.+Version automatically set by release.yml)" CMakeLists.txt)"
+          if [[ ! "$old_version" =~ ^[0-9]+[.][0-9]+[.][0-9]+$ ]]; then
+            echo "::error::Invalid old_version: $old_version"
+            exit 1
+          fi
           if ! dpkg --compare-versions "$VERSION" gt "$old_version"; then
             echo "::error::New version $VERSION must be greater than older version $old_version"
             exit 1
